### ISSUE TITLE
Axios is required.

### ISSUE THREAD

**Issue by mateusmx** [dropzone-ui/dropzone-ui-react#266]
Hi there, as always, this is an amazing development you have over here. But I'm currently developing an application with the Backend using TypeGraphql so no need for axios. And I did not had it installed in the front-end but suddenly when I was implementing the dropzone component I got this error: 

![image](https://user-images.githubusercontent.com/14305038/151645640-86d12a18-2e88-46fa-bc2e-54c965bcbf9c.png)

Which kind of force me to install axios. 

Is there any chance we can make the package 'axios' independent ? 

I placed it as a bug, but if is not up to you guys, feel free to close it.

Let me know if I can help you somehow.

@JinSSJ3 you already have my email so feel free to drop any question and if you like to pair also let me know.

Regards,

Pablo.

**Comment by JinSSJ3** [comment]
Hi pablo,

Thanks for your valuable feedback. 
Due to the fact that dropzone-ui has an upload feature we cannot dispense with axios yet. 
Currently we are working on adding some new features like the percentage progress on uploading and the possibility to abort the uploading. These features can not be done without axios so far, since [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) API doesn't support that yet. 

We are considering the idea to implement the upload feature 🚋 our way (maybe with XMLHttpRequest) and it will be done in some near future. Or maybe to include axios as regular dependency, so users don't need to install it manually (maybe not, it can produce to have 2 copies of axios if users install it manually for other operations).
Be sure that once we do it 🚀 , we'll notify you. So, for now, we kindly ask you to install axios despite you don't need it. Sorry 🙏  for the inconvenience 🚥.

Best,
Jin

**Comment by mateusmx** [comment]
Got it Jin, thanks for the fast reply my friend. I'll close the ticket then ! 

Regards,

Pablo.
