### ISSUE TITLE
The content in the children prop should be visible always

### ISSUE THREAD

**Issue by cannontechnology** [dropzone-ui/dropzone-ui-react#476]
The content in the children's prop should be visible always so you can add custom content when there are no items.  This would allow you to add a image and anything else you want to the dropzone when it loads.  However, the children's prop only shows once you select items to upload.

- Prop Name: children
- Prop Type: Node
- Prop Desc: The content of the component. Normally a list of FileItem components or a label

**Comment by JinSSJ3** [comment]
Hey there @cannontechnology . Thanks for notifying us about this issue.

We've just solved the children problem in a new version of 🚀  [@dropzone-ui/react](https://www.npmjs.com/package/@dropzone-ui/react) (V.6.7.10), we also updated the examples. Please give it a try and let us know if there is something missing in order to fix the issue.

Thanks in advance.

**Comment by cannontechnology** [comment]
@JinSSJ3 thank you very much for this update.  It's exactly what I was looking for.  Would be good to have a demo of it in the readme!

**Comment by cannontechnology** [comment]
Resolved.  Thanks
