### ISSUE TITLE
Can't use Dropzone in React 18 Typescript

### ISSUE THREAD

**Issue by rnkdsh** [dropzone-ui/dropzone-ui-react#497]
**Describe the bug**
Whenever I try to use Dropzone component with children it shows 

`Property 'children' does not exist on type 'IntrinsicAttributes & DropzoneProps'`

**To Reproduce**
1. Just try to use in project with React 18 and Typescript.

**Expected behavior**
It should allow me to use the Dropzone

**Screenshots**

<img width="1579" alt="Screenshot 2022-09-17 at 12 23 20 PM" src="https://user-images.githubusercontent.com/16722278/190844717-d9ac7598-edd3-4755-82f1-083bbd086634.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Any
 - Version: 6.7.10

**Comment by JinSSJ3** [comment]
Hey @rnkdsh !! Thanks for the alert.
This issue was solved some minutes ago in the latest version that we've just 🚀  deployed: @dropzone-ui/react [v.6.7 12](https://www.npmjs.com/package/@dropzone-ui/react)
Sorry for the inconvenience and please reinstall the package and let us know if it worked 👍 .

**Comment by rnkdsh** [comment]
Wow amazing, just updated and it's fixed 🥳
Thanks for the quick reply and fix 👍🏻
