### ISSUE TITLE
Last deleted item always comming back

### ISSUE THREAD

**Issue by LeninBoccardo** [dropzone-ui/dropzone-ui-react#565]
Everytime I select multiple itens just for view, not upload, and I delete them to select new ones, the last deleted file comes back with selected files.
e.g.: I select files: 'a', 'b', 'c', and I delete all, being 'c' the last one deleted. Then I select 'd' and 'e', in this new selection, file 'c' appears in the list too.

Anyone has already seen something like this? And how could I solve it?
Note: I used the complete example to make a custom dropzone. In my case, the file list appears above dropzone, not inside.

**Comment by JinSSJ3** [comment]
Hey there @LeninBoccardo !!!
Thanks for creating the issue. 

Unfortunately we couldn't reproduce the behaviour you described. As you can see in the video above we used the [complete example](https://codesandbox.io/s/complete-946hz?file=/src/App.js) .

In order to help you, we kindly ask you to provide us a link to a git repo or a codesandbox (you can fork the "complete example") or even a screenshot of the code.
Thanks in advance.

https://user-images.githubusercontent.com/43678736/208829225-65602331-3fe3-47c7-8830-99b488bbfea2.mp4

**Comment by LeninBoccardo** [comment]
The project I'm working is from my company, then I can't provide the full code but some screenshots are allowed: 
![image](https://user-images.githubusercontent.com/55263449/208898403-a26bf690-819a-401e-9661-9843eb138279.png)
![image](https://user-images.githubusercontent.com/55263449/208898541-260dc0fc-d86b-4557-85e7-8249a1a01021.png)
![image](https://user-images.githubusercontent.com/55263449/208898660-de7faad2-4c8f-4fea-8077-173083e5536d.png)
![image](https://user-images.githubusercontent.com/55263449/208898821-308bf896-f2af-4eab-aba1-9d9d29e09755.png)
![image](https://user-images.githubusercontent.com/55263449/208898856-bf74e653-f852-4e2d-8935-c5f5bc4ed0d9.png)
![image](https://user-images.githubusercontent.com/55263449/208899248-218d0e96-8fb6-44d6-9072-374fdccb8468.png)


First picture is the variables that control states
Second one is the functions used to handle the dropzone and file Items
Third is the dropzone code
Fourty and fifthy is the FileItems list
Last one is the result

**Comment by LeninBoccardo** [comment]
https://user-images.githubusercontent.com/55263449/208902252-0a125c28-776f-47d7-ae82-0c724130a24b.mp4

This is a video showing the problem

**Comment by JinSSJ3** [comment]
Hi @LeninBoccardo !!
After checking your code in the screenshots and testing it (we rewrited it in a test project 👀 ).
We found that the error is located in the 2nd picture in the last line. Instead of:
```jsx
  const getFiles = () => filesData.length && filesData.map((f) => f.file);
```

you should write:
```jsx
  const getFiles = () =>  filesData.map((f) => f.file);
```
Because the value of the `filesData.length` is `0` when the user deletes all the files one by one, the function `getFiles` will not be executed correctly and will cause a bug.
Try changing that line and tell us if that worked for you.

Thanks in advance.

**Comment by LeninBoccardo** [comment]
@JinSSJ3 , I can't believe such a tiny code was causing all trouble. It worked for me, thanks for your help.
