### ISSUE TITLE
Version 7.0.2 "Compiled with problems"

### ISSUE THREAD

**Issue by adihanifsdr** [dropzone-ui/dropzone-ui-react#594]
Hello,

I encountered a syntax error while using the '@dropzone-ui/react' library in my project. The error message is:

```
Compiled with problems:

ERROR in ./node_modules/@dropzone-ui/react/build/index.es.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\Users\adiha\OneDrive\Desktop\projects\projects_frontend\node_modules\@dropzone-ui\react\build\index.es.js: Identifier 'e' has already been declared. (1:447)
```

I have tried the following steps to resolve the issue, but none of them worked:

1. Updating the package to the latest version.
2. Uninstalling and reinstalling the package.

I am using the following dependencies:

```

"dependencies": {
    "@dropzone-ui/react": "^7.0.2",
    "@react-oauth/google": "^0.9.0",
    "@reduxjs/toolkit": "^1.8.6",
    "@tinymce/tinymce-react": "^4.2.0",
    "aws-sdk": "^2.1361.0",
    "axios": "^0.26.1",
    "dropzone": "^6.0.0-beta.2",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "moment-timezone": "^0.5.37",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-feather": "^2.0.10",
    "react-image-gallery": "^1.2.11",
    "react-loading-skeleton": "^3.1.0",
    "react-nl2br": "^1.0.4",
    "react-redux": "^8.0.4",
    "react-router-dom": "^6.3.0",
    "react-scripts": "^5.0.0",
    "react-show-more-text": "^1.6.2",
    "react-slick": "^0.29.0",
    "react-tag-input": "^6.8.1",
    "react-waypoint": "^10.3.0",
    "redux-persist": "^6.0.0",
    "slick-carousel": "^1.8.1",
    "underscore": "^1.13.6"
  },
```

It would be great if you could look into this issue and provide some guidance on how to resolve it. If you need any further information or details, please let me know. 

Thank you for your assistance!

**Comment by JinSSJ3** [comment]
Hi @adihanifsdr !!

Thanks for the alert. 
We will give it a look and will answer you as soon as possible to help you solving the issue!

Thnaks in advance.

**Comment by adihanifsdr** [comment]
Any update?

> Hi @adihanifsdr !!
> 
> Thanks for the alert. We will give it a look and will answer you as soon as possible to help you solving the issue!
> 
> Thnaks in advance.

**Comment by JinSSJ3** [comment]
Hey there @adihanifsdr ! ✋ 

Sorry for the delay, we've been a bit busy developing new features and working on other improvements. 🔨 ⚡ 

We've solved the issue. We have 2 options for you:
- You can either edit your package.json and remove "@dropzone-ui/react" and add "@files-ui/react" as  a dependency.
- Or you can upgrade the @dropzone-ui/react dependency from version 7.0.2 to 7.0.4. We've just published the new version 🚀 

Please let us know if this works for you.
Thanks in advance!


👀 
FYI: The problem was that when migrating from [@dropzone-ui/react](https://www.npmjs.com/package/@dropzone-ui/react) to [@files-ui/react](https://www.npmjs.com/package/@files-ui/react) we haven´t refactores some configuration for build process. There are some plugings for handling sass files in packages and since this package is just a wrapper of files-ui/react, we should've avoided to set the sass configuration line since there is no need to complie sass files again. Not removing that configuration caused to duplicate the function that injects the styles and produced the error you captured: "Identifier 'e' has already been declared."
